// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb0zbyKzm-QMd8K7gE5h8lsH4hQGwovC0',
    appId: '1:820571227201:web:35a176c9523059e425f2c0',
    messagingSenderId: '820571227201',
    projectId: 'clean-archeticture-movies',
    authDomain: 'clean-archeticture-movies.firebaseapp.com',
    storageBucket: 'clean-archeticture-movies.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPYBDwzVsSQl-rkdNb72-5VSJyJ8NQCyg',
    appId: '1:820571227201:android:471f57a67544af7425f2c0',
    messagingSenderId: '820571227201',
    projectId: 'clean-archeticture-movies',
    storageBucket: 'clean-archeticture-movies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1yRd2EiX97I8GUl9qjj676cbYRbgb6I',
    appId: '1:820571227201:ios:fbe6153287ff901525f2c0',
    messagingSenderId: '820571227201',
    projectId: 'clean-archeticture-movies',
    storageBucket: 'clean-archeticture-movies.appspot.com',
    iosClientId: '820571227201-nfmt0j1hob0ei3o9v73n6tr6m5ukbera.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchetictureMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM1yRd2EiX97I8GUl9qjj676cbYRbgb6I',
    appId: '1:820571227201:ios:fbe6153287ff901525f2c0',
    messagingSenderId: '820571227201',
    projectId: 'clean-archeticture-movies',
    storageBucket: 'clean-archeticture-movies.appspot.com',
    iosClientId: '820571227201-nfmt0j1hob0ei3o9v73n6tr6m5ukbera.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchetictureMovies',
  );
}
